sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
  - pypy3
env:
  - SYMPY_SRC=sympy-0.7.6 CYTHON="true"
  - SYMPY_SRC=sympy-0.7.6 CYTHON="false"
  - SYMPY_SRC=sympy-0.7.5 CYTHON="false"
  - SYMPY_SRC=master CYTHON="false"
matrix:
    allow_failures:
      - python: 3.4
      - python: 3.5
      - python: pypy3
      - env: SYMPY_SRC=sympy-0.7.5 CYTHON="false"
      - env: SYMPY_SRC=master CYTHON="false"
before_install:
  - if [[ "$CYTHON" == "true" ]]; then
      pip install cython;
    fi
  - pip install unittest2
  - pip install pexpect
  - pip install git+https://github.com/sympy/sympy.git@$SYMPY_SRC
install:
  - sed -i "s/'sympy==[0-9]\.[0-9]\.[0-9]', //" setup.py
  - python setup.py install
script:
  - python setup.py test
  - python mathics/test.py;
notifications:
    email: false
