language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  - SYMPY_SRC=sympy-0.7.3
  - SYMPY_SRC=master
matrix:
  include:
    - python: 2.7
      env:
        - SYMPY_SRC=sympy-0.7.3
        - TEST_DOC="true"
  allow_failures:
    - env: SYMPY_SRC=master
before_install:
  - if [[ "$TEST_DOC" == "true" ]]; then
      sudo apt-get update -qq;
      sudo apt-get install -qq asymptote texlive-full imagemagick;
    fi
  - pip install --use-mirrors git+https://github.com/sympy/sympy.git@$SYMPY_SRC
install:
  - python setup.py install
script:
  - if [[ "$TEST_DOC" == "true" ]]; then
      python mathics/test.py -o;
      python mathics/test.py -t;
      cd mathics/doc/;
      ./images.sh;
      cd tex/;
      make latex;
      cd ../../../;
    else
      python mathics/test.py;
    fi
notifications:
  email: false
