language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - pypy3
env:
  global:
    - SYMPY_SRC=sympy-1.0
    - DOC="false"
    - NUMPY="false"
    - SKIMAGE="false"
  matrix:
    - CYTHON="false"
    - CYTHON="true"
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: DOC="true" CYTHON="false"
    - python: 3.5
      env: DOC="true" CYTHON="false"
    - python: 2.7
      env: SYMPY_SRC=master CYTHON="false"
    - python: 3.5
      env: SYMPY_SRC=master CYTHON="false"
    - python: 2.7
      env: NUMPY="true" SKIMAGE="true"
    - python: 3.5
      env: NUMPY="true" SKIMAGE="true"
  exclude:
    # PyPy is not compatible with Cython
    - python: pypy
      env: CYTHON="true"
    - python: pypy3
      env: CYTHON="true"
  allow_failures:
    - python: 3.2
    - python: pypy3
    - env: SYMPY_SRC=master CYTHON="false"
    - env: DOC="true" CYTHON="false"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qq
  - if [[ "$DOC" == "true" ]]; then
      sudo apt-get install -qq asymptote imagemagick texlive-latex-extra texlive-latex3 texlive-fonts-recommended latexmk;
    fi
  - if [[ "$cython" == "true" ]]; then
      pip install cython;
    fi

  # install condra
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     fi
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - hash -r
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   # Useful for debugging any issues with conda
   - conda info -a

   # Replace dep1 dep2 ... with your dependencies
   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy matplotlib scipy skimage
   - source activate test-environment

  - if [[ "$NUMPY" == "true" ]]; then
      sudo apt-get install -qq python-numpy;
    fi
  - if [[ "$SKIMAGE" == "true" ]]; then
      sudo apt-get install -qq python-matplotlib python-scipy &&
      pip install scikit-image;
    fi
  - pip install unittest2
  - pip install pexpect
  - pip install git+https://github.com/sympy/sympy.git@$SYMPY_SRC
install:
  - sed -i "s/'sympy==[0-9]\.[0-9]\.[0-9]', //" setup.py
  - if [[ "$DOC" == "true" ]]; then python setup.py develop; else python setup.py install; fi
script:
  - python setup.py test
  - if [[ "$DOC" == "true" ]]; then
      python mathics/test.py -o &&
      python mathics/test.py -t &&
      cd mathics/doc/ &&
      ./images.sh &&
      cd tex/ &&
      make latex;
    else
      python mathics/test.py;
    fi
notifications:
    email: false
